import type { ContactLocationGroup, ContactSocialLink } from "./types";

export const contactLocationGroups: ContactLocationGroup[] = [
  {
    id: "sede-principal",
    title: "Sede principal",
    locations: [
      {
        id: "sede-principal-sp",
        name: "Gaviões da Fiel Sede Principal",
        address: "R. Cristina Tomás, 183",
        neighborhood: "Bom Retiro",
        zipCode: "01129-020",
        city: "São Paulo-SP",
        phone: "(11) 3221-2066",
        mapQuery: "R. Cristina Tomás, 183 - Bom Retiro, São Paulo - SP, 01129-020",
      },
    ],
  },
  {
    id: "subsedes",
    title: "Subsedes",
    locations: [
      {
        id: "subsede-abc",
        name: "Gaviões da Fiel SubSede ABC",
        address: "Rua dos Coqueiros, 100",
        neighborhood: "Campestre",
        zipCode: "090080-010",
        city: "Santo André-SP",
        foundation: "01/10/1992",
        phone: "Não informado",
        mapQuery:
          "Rua dos Coqueiros, 100, Campestre, Santo André - SP, 090080-010",
      },
      {
        id: "subsede-baixada",
        name: "Gaviões da Fiel SubSede Baixada",
        address: "Marechal Pego Júnior, 61",
        neighborhood: "Vila Nova",
        zipCode: "11013-500",
        city: "Santos-SP",
        foundation: "05/06/1994",
        phone: "(13) 98883-1565",
        mapQuery: "Marechal Pego Júnior, 61, Vila Nova, Santos - SP, 11013-500",
      },
      {
        id: "subsede-brasilia",
        name: "Gaviões da Fiel SubSede Brasília",
        address: "SDE. Q 01. CONJ B. LOJA 05",
        zipCode: "72145-102",
        city: "Taguatinga-DF",
        foundation: "13/05/1993",
        phone: "(61) 99416-0911",
        mapQuery: "SDE Q 01 CONJ B LOJA 05, Taguatinga - DF, 72145-102",
      },
      {
        id: "subsede-guarulhos",
        name: "Gaviões da Fiel SubSede Guarulhos",
        address: "Rua Ladeira Campos Sales, 37",
        neighborhood: "Centro",
        zipCode: "07012-013",
        city: "Guarulhos-SP",
        foundation: "25/06/2000",
        phone: "Não informado",
        mapQuery: "Rua Ladeira Campos Sales, 37, Centro, Guarulhos - SP",
      },
      {
        id: "subsede-indaiatuba",
        name: "Gaviões da Fiel SubSede Indaiatuba",
        address: "Rua João Peron, 220",
        neighborhood: "Jardim Morada do Sol",
        zipCode: "13346-550",
        city: "Indaiatuba-SP",
        foundation: "01/07/2001",
        phone:
          "(11) 99117-7216 / (19) 99216-6138 / (19) 99985-3776 / (19) 99421-7195",
        mapQuery:
          "Rua João Peron, 220, Jardim Morada do Sol, Indaiatuba - SP, 13346-550",
      },
      {
        id: "subsede-japao",
        name: "Gaviões da Fiel SubSede Japão",
        address: "Chiryu shi, Showa 9-4, Chiryu Danchi 12-201",
        zipCode: "472-0011",
        city: "Aichi Ken - Japão",
        foundation: "18/09/2005",
        phone: "Não informado",
        mapQuery: "Chiryu Danchi 12-201, Showa 9-4, Chiryu shi, Aichi Ken, Japan",
      },
      {
        id: "subsede-jundiai",
        name: "Gaviões da Fiel SubSede Jundiaí",
        address: "Rua Maringá, 34",
        neighborhood: "Vila Maringá",
        zipCode: "13210-050",
        city: "Jundiaí-SP",
        foundation: "05/09/2010",
        phone: "(11) 99758-1117",
        mapQuery: "Rua Maringá, 34, Vila Maringá, Jundiaí - SP, 13210-050",
      },
      {
        id: "subsede-piracicaba",
        name: "Gaviões da Fiel SubSede Piracicaba",
        address: "Praça Antônio de Pádua Dutra, 1055",
        neighborhood: "Centro",
        zipCode: "13400-030",
        city: "Piracicaba-SP",
        foundation: "01/07/1999",
        phone: "(19) 99608-1246 Márcio / (19) 99786-1447 Ezequiel",
        mapQuery:
          "Praça Antônio de Pádua Dutra, 1055, Centro, Piracicaba - SP, 13400-030",
      },
      {
        id: "subsede-rio-claro",
        name: "Gaviões da Fiel SubSede Rio Claro",
        address:
          "Rua M-13 entre avenida M19 e M-21, 326 (em frente a lagoa seca)",
        neighborhood: "Cervezão",
        zipCode: "13505-280",
        city: "Rio Claro-SP",
        foundation: "04/04/2007",
        phone: "(19) 97126-3882",
        mapQuery:
          "Rua M-13, 326, Cervezão, Rio Claro - SP, 13505-280, em frente a lagoa seca",
      },
      {
        id: "subsede-sorocaba",
        name: "Gaviões da Fiel SubSede Sorocaba",
        address: "Rua Judith R. Tavares, 64",
        neighborhood: "Jardim Santa Fé",
        zipCode: "18031-360",
        city: "Sorocaba-SP",
        foundation: "23/09/1999",
        phone: "(15) 99190-2739",
        mapQuery:
          "Rua Judith R. Tavares, 64, Jardim Santa Fé, Sorocaba - SP, 18031-360",
      },
      {
        id: "subsede-vale-paraiba",
        name: "Gaviões da Fiel SubSede Vale do Paraíba",
        address: "Avenida Carlos Nunes de Paula, 1202",
        neighborhood: "Jardim Imperial",
        zipCode: "12234-000",
        city: "São José dos Campos-SP",
        foundation: "06/12/2003",
        phone: "(12) 98832-5172 João Paulo / (12) 98116-5323 Wallace",
        mapQuery:
          "Avenida Carlos Nunes de Paula, 1202, Jardim Imperial, São José dos Campos - SP, 12234-000",
      },
    ],
  },
  {
    id: "pontos-oficiais",
    title: "Pontos de encontro oficiais",
    locations: [
      {
        id: "ponto-alagoas",
        name: "Alagoas",
        address: "Rua Camaragibe, 97",
        neighborhood: "Ouro Preto",
        zipCode: "57038-240",
        city: "Maceió-AL",
        foundation: "28/11/2007",
        phone: "(82) 99308-2634",
        mapQuery: "Rua Camaragibe, 97, Ouro Preto, Maceió - AL, 57038-240",
      },
      {
        id: "ponto-londrina",
        name: "Londrina",
        address: "Rua Serra dos Pirineus, 1135",
        neighborhood: "Jardim Bandeirantes",
        zipCode: "86065-610",
        city: "Londrina-PR",
        foundation: "15/11/2012",
        phone: "(43) 99665-9062 Diego Correia / (43) 99183-7341 Diego Gomes",
        mapQuery:
          "Rua Serra dos Pirineus, 1135, Jardim Bandeirantes, Londrina - PR, 86065-610",
      },
      {
        id: "ponto-presidente-prudente",
        name: "Presidente Prudente",
        address: "Rua Pioneiro Fortunato Lodron, 145",
        neighborhood: "Jardim Santa Mônica",
        zipCode: "19045-840",
        city: "Presidente Prudente-SP",
        foundation: "23/02/2008",
        phone: "(18) 99607-3193",
        mapQuery:
          "Rua Pioneiro Fortunato Lodron, 145, Jardim Santa Mônica, Presidente Prudente - SP, 19045-840",
      },
      {
        id: "ponto-taubate",
        name: "Taubaté",
        address: "Avenida Sagrado Coração de Jesus, 95",
        neighborhood: "Vila São Geraldo",
        zipCode: "12062-050",
        city: "Taubaté-SP",
        foundation: "09/07/2011",
        phone: "(12) 97409-5366",
        mapQuery:
          "Avenida Sagrado Coração de Jesus, 95, Vila São Geraldo, Taubaté - SP, 12062-050",
      },
    ],
  },
];

export const contactSocialLinks: ContactSocialLink[] = [
  {
    id: "instagram",
    label: "Instagram",
    href: "https://www.instagram.com/gavioesoficial/",
  },
  {
    id: "youtube",
    label: "YouTube",
    href: "https://www.youtube.com/@gavioesoficial",
  },
  {
    id: "twitter",
    label: "X / Twitter",
    href: "https://x.com/gavioesoficial",
  },
  {
    id: "facebook",
    label: "Facebook",
    href: "https://www.facebook.com/GavioesOficial",
  },
];
